export const SOURCE_CATEGORIES = [
  {
    id: 'per-deal',
    label: 'Per-Deal Source Links',
    sources: [
      { name: 'TechCrunch', description: '"Billion-Dollar Infrastructure Deals in the AI Boom"', date: 'Feb 28, 2026', url: 'https://techcrunch.com/2026/02/28/billion-dollar-infrastructure-deals-ai-boom-data-centers-openai-oracle-nvidia-microsoft-google-meta/' },
      { name: 'AMD Press Release', description: '"AMD and Meta Announce Expanded Strategic Partnership"', date: 'Feb 24, 2026', url: 'https://www.amd.com/en/newsroom/press-releases/2026-2-24-amd-and-meta-announce-expanded-strategic-partnersh.html' },
      { name: 'Reuters', description: '"Broadcom Signs Long-Term Deal to Develop Google\'s Custom AI Chips"', date: 'Apr 6, 2026', url: 'https://www.reuters.com/business/broadcom-signs-long-term-deal-develop-googles-custom-ai-chips-2026-04-06/' },
      { name: 'Augment Market', description: '"CoreWeave Has Now Signed the Four Biggest AI Labs"', date: null, url: 'https://augment.market/pulse/coreweave-has-now-signed-the-four-biggest-ai-labs' },
      { name: 'Reuters', description: '"Companies Pouring Billions to Advance AI Infrastructure"', date: 'Apr 9, 2026', url: 'https://www.reuters.com/business/autos-transportation/companies-pouring-billions-advance-ai-infrastructure-2026-04-09/' },
      { name: 'Reuters', description: '"CoreWeave, NVIDIA Sign $6.3B Cloud Computing Capacity Order"', date: 'Sep 15, 2025', url: 'https://www.reuters.com/business/coreweave-nvidia-sign-63-billion-cloud-computing-capacity-order-2025-09-15/' },
      { name: 'Fast Company', description: '"Computing\'s Most Innovative Companies 2026"', date: '2026', url: 'https://www.fastcompany.com/91497091/computing-most-innovative-companies-2026' },
      { name: 'Gilder Report', description: '"Broadcom and the Rise of Custom AI Silicon"', date: null, url: 'https://www.gilderreport.com/broadcom-and-the-rise-of-custom-ai-silicon/' },
      { name: 'Los Angeles Times', description: '"NVIDIA Invests Additional $2 Billion in CoreWeave"', date: 'Jan 26, 2026', url: 'https://www.latimes.com/business/story/2026-01-26/nvidia-invests-additional-2-billion-in-coreweave' },
      { name: 'NVIDIA Investor Relations', description: '"NVIDIA and Nebius Partner to Scale Full-Stack AI Cloud"', date: 'Mar 2026', url: 'https://investor.nvidia.com/news/press-release-details/2026/NVIDIA-and-Nebius-Partner-to-Scale-Full-Stack-AI-Cloud/' },
      { name: 'Saturn Cloud', description: 'GPU Cloud Comparison Report', date: null, url: 'https://saturncloud.io/reports/gpu-cloud-comparison-report/' },
      { name: 'Siebert Financial', description: '"NVIDIA\'s $57 Billion Flex and the Death of the AI Bubble Call"', date: null, url: 'https://blog.siebert.com/nvidias-57-billion-flex-and-the-death-of-the-ai-bubble-call' },
      { name: 'Oracle News', description: '"Oracle and AMD Expand Partnership"', date: 'Oct 14, 2025', url: 'https://www.oracle.com/news/announcement/ai-world-oracle-and-amd-expand-partnership-to-help-customers-achieve-next-generation-ai-scale-2025-10-14/' },
      { name: 'AMD Investor Relations', description: '"AMD Unveils Vision for an Open AI Ecosystem"', date: '2025', url: 'https://ir.amd.com/news-events/press-releases/detail/1255/amd-unveils-vision-for-an-open-ai-ecosystem-detailing-new-silicon-software-and-systems-at-advancing-ai-2025' },
      { name: 'Silicon Republic', description: '"Anthropic, Google, Broadcom Announce 3.5GW TPU Deal"', date: null, url: 'https://www.siliconrepublic.com/machines/anthropic-google-broadcom-announce-3-5gw-tpu-deal' },
      { name: 'Jon Peddie Research', description: '"Broadcom\'s $100B Custom Silicon Bet"', date: null, url: 'https://www.jonpeddie.com/news/broadcoms-100b-custom-silicon-bet/' },
      { name: 'Futurum Group', description: '"Anthropic\'s Gigawatt-Scale TPU Deal with Broadcom Creates a Structural Advantage"', date: null, url: 'https://futurumgroup.com/insights/anthropics-gigawatt-scale-tpu-deal-with-broadcom-creates-a-structural-advantage/' },
      { name: 'The Next Web', description: '"CoreWeave Agrees Multi-Year GPU Cloud Deal with Anthropic"', date: null, url: 'https://thenextweb.com/news/coreweave-has-agreed-a-multi-year-gpu-cloud-deal-with-anthropic-to-power-claude-at-production-scale-its-second-major-ai-infrastructure-announcement-in-48-hours' },
    ],
  },
  {
    id: 'sec-filings',
    label: 'SEC Filings & Investor Relations',
    sources: [
      { name: 'NVIDIA SEC Filings', description: '10-K, 10-Q, 8-K filings — data center revenue, supply agreements, related-party transactions', date: 'Current', url: 'https://investor.nvidia.com/financial-info/sec-filings' },
      { name: 'AMD SEC Filings', description: '10-K, 10-Q, 8-K filings — data center segment, customer concentration, ASIC arrangements', date: 'Current', url: 'https://ir.amd.com/sec-filings' },
      { name: 'Broadcom SEC Filings', description: '10-K, 10-Q, 8-K filings — custom ASIC revenue, hyperscaler customer disclosures', date: 'Current', url: 'https://investors.broadcom.com/sec-filings' },
      { name: 'Marvell SEC Filings', description: '10-K, 10-Q, 8-K filings — AI ASIC program disclosures, data center revenue', date: 'Current', url: 'https://investor.marvell.com/sec-filings' },
      { name: 'Intel SEC Filings', description: '10-K, 10-Q, 8-K filings — foundry revenue, Gaudi accelerator program', date: 'Current', url: 'https://www.intc.com/filings-reports/sec-filings' },
      { name: 'TSMC Annual Reports', description: 'Annual report and investor presentations — advanced packaging, CoWoS capacity, customer mix', date: 'Current', url: 'https://investor.tsmc.com/english/annual-reports' },
      { name: 'CoreWeave SEC Filings', description: 'S-1 and post-IPO 10-K filings — GPU fleet, customer contracts, NVIDIA relationship', date: 'Current', url: 'https://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&company=coreweave&CIK=&type=&dateb=&owner=include&count=40&search_text=&action=getcompany' },
      { name: 'Oracle SEC Filings', description: '10-K, 10-Q, 8-K filings — Stargate commitment, cloud infrastructure capex', date: 'Current', url: 'https://investor.oracle.com/sec-filings/default.aspx' },
      { name: 'Microsoft SEC Filings', description: '10-K, 10-Q, 8-K filings — Azure AI infrastructure, OpenAI partnership, capex', date: 'Current', url: 'https://www.microsoft.com/en-us/investor/sec-filings.aspx' },
      { name: 'Alphabet/Google SEC Filings', description: '10-K, 10-Q, 8-K filings — TPU program, GCP infrastructure, Broadcom/Marvell ASIC contracts', date: 'Current', url: 'https://abc.xyz/investor/' },
      { name: 'Amazon SEC Filings', description: '10-K, 10-Q, 8-K filings — AWS Trainium/Inferentia programs, capex guidance', date: 'Current', url: 'https://ir.aboutamazon.com/sec-filings/default.aspx' },
      { name: 'Meta SEC Filings', description: '10-K, 10-Q, 8-K filings — MTIA program, data center capex, GPU procurement', date: 'Current', url: 'https://investor.fb.com/sec-filings/default.aspx' },
    ],
  },
  {
    id: 'epoch-ai',
    label: 'Epoch AI Datasets',
    sources: [
      { name: 'Epoch AI — AI Chip Sales Data Explorer', description: 'Quarterly AI accelerator shipments and revenue by manufacturer (NVIDIA, Google, Amazon, AMD, Huawei). H100-equivalent compute units, cost, power. CC-BY.', date: 'Updated monthly', url: 'https://epoch.ai/data/ai-chip-sales' },
      { name: 'Epoch AI — AI Chip Sales Documentation', description: 'Full methodology, per-manufacturer estimation approach, NVIDIA revenue decomposition tables', date: 'Current', url: 'https://epoch.ai/data/ai-chip-sales-documentation' },
      { name: 'Epoch AI — AI Chip Owners', description: 'Estimates of how AI chips are distributed among hyperscalers, AI labs, and neoclouds', date: 'Updated Apr 2026', url: 'https://epoch.ai/data/ai-chip-owners' },
      { name: 'Epoch AI — Frontier Data Centers', description: 'Open database of large AI data centers tracked via satellite/permit data. Power, compute, construction timelines.', date: 'Updated Apr 2026', url: 'https://epoch.ai/data/frontier-data-centers' },
      { name: 'Epoch AI — GPU Clusters Database', description: '500+ GPU clusters and supercomputers, including AI training/inference facilities', date: 'Updated Apr 2026', url: 'https://epoch.ai/data/gpu-clusters' },
      { name: 'Epoch AI — ML Hardware Database', description: 'Key specs on 170+ AI accelerators — GPUs, TPUs, custom ASICs', date: 'Updated Dec 2025', url: 'https://epoch.ai/data/machine-learning-hardware' },
      { name: 'Epoch AI — AI Companies', description: 'Revenue, funding, staff, and compute for major AI companies', date: 'Updated Apr 2026', url: 'https://epoch.ai/data/ai-companies' },
      { name: 'Epoch AI — Supply Chain Constraints Analysis', description: 'CoWoS packaging, HBM, and advanced logic capacity constraints in 2025', date: '2025', url: 'https://epoch.ai/data-insights/ai-chip-supply-chain-constraints' },
      { name: 'Epoch AI — Global AI Compute Growth', description: 'Finding: global AI compute capacity doubling every ~7 months', date: 'Current', url: 'https://epoch.ai/data-insights/ai-chip-production' },
    ],
  },
  {
    id: 'industry-research',
    label: 'Industry Research & Market Data',
    sources: [
      { name: 'Semiconductor Industry Association (SIA)', description: 'Monthly semiconductor sales data, policy briefs, trade statistics', date: 'Monthly', url: 'https://www.semiconductors.org/resources/' },
      { name: 'SEMI', description: 'Fab equipment spending, silicon shipment data, industry reports', date: 'Quarterly', url: 'https://www.semi.org/en/resources/market-data' },
      { name: 'WSTS (World Semiconductor Trade Statistics)', description: 'Official global semiconductor revenue and forecast data', date: 'Monthly', url: 'https://www.wsts.org/' },
      { name: 'TrendForce', description: 'Quarterly DRAM/NAND/foundry reports, AI ASIC shipment forecasts', date: 'Quarterly', url: 'https://www.trendforce.com/' },
      { name: 'Omdia (Informa Tech)', description: 'GPU market share, AI chip customer allocation estimates (e.g., MI300X customer splits)', date: 'Ongoing', url: 'https://omdia.tech.informa.com/' },
      { name: 'IDC', description: 'Semiconductor, server, and data center market trackers', date: 'Quarterly', url: 'https://www.idc.com/' },
      { name: 'Gartner', description: 'AI infrastructure forecasts, semiconductor market analysis', date: 'Ongoing', url: 'https://www.gartner.com/en/industries/high-tech' },
      { name: 'TechInsights', description: 'Die-level analysis, wafer fab capacity, process node data', date: 'Ongoing', url: 'https://www.techinsights.com/' },
      { name: "Dell'Oro Group", description: 'Data center capex, networking equipment, cloud infrastructure trackers', date: 'Quarterly', url: 'https://www.delloro.com/' },
      { name: 'Yole Group', description: 'Advanced packaging, 3D IC, chiplet analysis and market reports', date: 'Ongoing', url: 'https://www.yolegroup.com/' },
      { name: 'VLSI Research', description: 'Chip equipment market share, fabrication economics', date: 'Ongoing', url: 'https://vlsiresearch.com/' },
      { name: 'SemiAnalysis', description: 'In-depth semiconductor analysis (Dylan Patel). GPU supply chains, custom ASIC economics, CoWoS capacity, HBM supply/demand. Widely cited by institutional investors.', date: 'Weekly', url: 'https://www.semianalysis.com/' },
      { name: 'Fabricated Knowledge', description: 'Semiconductor investment-focused newsletter', date: 'Ongoing', url: 'https://www.fabricatedknowledge.com/' },
    ],
  },
  {
    id: 'earnings',
    label: 'Earnings Calls & Investor Presentations',
    sources: [
      { name: 'NVIDIA GTC Keynotes & Earnings Transcripts', description: 'Primary source for GPU demand commentary, hyperscaler customer disclosures, and supply chain outlook', date: 'Quarterly', url: 'https://investor.nvidia.com/events-and-presentations/events-and-presentations' },
      { name: 'Broadcom Earnings Call Transcripts', description: 'Custom ASIC revenue guidance, hyperscaler XPU program disclosures, TAM estimates. Available via SEC EDGAR 8-K filings.', date: 'Quarterly', url: null },
      { name: 'AMD "Advancing AI" Event Transcripts', description: 'MI300X/MI350 customer adoption, data center revenue, Instinct GPU roadmap', date: 'Annual', url: 'https://ir.amd.com/news-events/events-presentations' },
      { name: 'TSMC Quarterly Earnings Calls', description: 'CoWoS advanced packaging capacity, customer demand visibility, leading-edge node economics', date: 'Quarterly', url: 'https://investor.tsmc.com/english/quarterly-results' },
      { name: 'Marvell Earnings & Investor Day', description: 'AI ASIC program progress, hyperscaler customer TAM projections, 2026–2028 revenue roadmap', date: 'Quarterly/Annual', url: 'https://investor.marvell.com/events-and-presentations' },
    ],
  },
  {
    id: 'government',
    label: 'Government & Trade Data',
    sources: [
      { name: 'U.S. Bureau of Industry and Security (BIS)', description: 'Export control rules affecting AI chip trade: Entity List, Advanced Computing Rule, chip export restrictions', date: 'Current', url: 'https://www.bis.gov/' },
      { name: 'SEC EDGAR Full-Text Search', description: 'Search all public filings for deal terms, supply agreements, related-party transactions', date: 'Current', url: 'https://efts.sec.gov/LATEST/search-index?q=' },
      { name: 'U.S. International Trade Commission DataWeb', description: 'Semiconductor import/export data by HTS code', date: 'Monthly', url: 'https://dataweb.usitc.gov/' },
    ],
  },
  {
    id: 'research-policy',
    label: 'Research & Policy Organizations',
    sources: [
      { name: 'Stanford HAI — AI Index Report', description: 'Annual report tracking compute trends, AI investment, policy developments. Free.', date: 'Annual', url: 'https://aiindex.stanford.edu/' },
      { name: 'Georgetown CSET', description: 'Semiconductor supply chain and AI policy research', date: 'Ongoing', url: 'https://cset.georgetown.edu/' },
      { name: 'RAND Corporation', description: 'Semiconductor and AI security analysis', date: 'Ongoing', url: 'https://www.rand.org/topics/semiconductors.html' },
    ],
  },
  {
    id: 'news-analysis',
    label: 'News & Analysis',
    sources: [
      { name: 'Reuters Technology', description: 'Ongoing coverage of AI infrastructure deals, hyperscaler capex, chip supply chains', date: 'Ongoing', url: 'https://www.reuters.com/technology/' },
      { name: 'Bloomberg Terminal', description: 'Semiconductor supply chain data, capex trackers, earnings estimates. Paid subscription.', date: 'Real-time', url: 'https://www.bloomberg.com/professional/' },
      { name: 'The Information', description: 'Exclusive AI/tech deal reporting, hyperscaler strategy coverage. Paid subscription.', date: 'Ongoing', url: 'https://www.theinformation.com/' },
      { name: 'Data Center Dynamics', description: 'AI datacenter capex analysis, hyperscaler power/build programs', date: 'Ongoing', url: 'https://www.datacenterdynamics.com/' },
      { name: 'Deloitte', description: '2026 Global Semiconductor Industry Outlook', date: '2026', url: 'https://www.deloitte.com/us/en/insights/industry/technology/technology-media-telecom-outlooks/semiconductor-industry-outlook.html' },
      { name: 'J.P. Morgan — "Eye on the Market"', description: 'AI capex cycle analysis (Cembalest). Available via J.P. Morgan Asset Management.', date: 'Periodic', url: null },
    ],
  },
]
