// Canonical source catalog.
// Schema contract for every entry:
//   name        publisher/brand, terse. Not the article title.
//   description sentence case, no quotation marks. Article title when applicable,
//               otherwise a short phrase describing the resource.
//   date        exactly one of: 'Mon YYYY' | 'YYYY' | null. Cadence words
//               (Quarterly/Ongoing/Current/etc.) are not dates — use null
//               and let the description carry cadence if it matters.
//   url         the link; null when no canonical URL exists (paid terminals,
//               private decks). Never an em-dash placeholder.
export const SOURCE_CATEGORIES = [
  {
    id: 'per-deal',
    label: 'Per-Deal Articles',
    sources: [
      { name: 'TechCrunch', description: 'Billion-dollar infrastructure deals in the AI boom', date: 'Feb 2026', url: 'https://techcrunch.com/2026/02/28/billion-dollar-infrastructure-deals-ai-boom-data-centers-openai-oracle-nvidia-microsoft-google-meta/' },
      { name: 'AMD Newsroom', description: 'AMD and Meta announce expanded strategic partnership', date: 'Feb 2026', url: 'https://www.amd.com/en/newsroom/press-releases/2026-2-24-amd-and-meta-announce-expanded-strategic-partnersh.html' },
      { name: 'Reuters', description: "Broadcom signs long-term deal to develop Google's custom AI chips", date: 'Apr 2026', url: 'https://www.reuters.com/business/broadcom-signs-long-term-deal-develop-googles-custom-ai-chips-2026-04-06/' },
      { name: 'Augment Market', description: 'CoreWeave has now signed the four biggest AI labs', date: null, url: 'https://augment.market/pulse/coreweave-has-now-signed-the-four-biggest-ai-labs' },
      { name: 'Reuters', description: 'Companies pouring billions to advance AI infrastructure', date: 'Apr 2026', url: 'https://www.reuters.com/business/autos-transportation/companies-pouring-billions-advance-ai-infrastructure-2026-04-09/' },
      { name: 'Reuters', description: 'CoreWeave, NVIDIA sign $6.3B cloud computing capacity order', date: 'Sep 2025', url: 'https://www.reuters.com/business/coreweave-nvidia-sign-63-billion-cloud-computing-capacity-order-2025-09-15/' },
      { name: 'Fast Company', description: "Computing's most innovative companies 2026", date: '2026', url: 'https://www.fastcompany.com/91497091/computing-most-innovative-companies-2026' },
      { name: 'Gilder Report', description: 'Broadcom and the rise of custom AI silicon', date: null, url: 'https://www.gilderreport.com/broadcom-and-the-rise-of-custom-ai-silicon/' },
      { name: 'Los Angeles Times', description: 'NVIDIA invests additional $2 billion in CoreWeave', date: 'Jan 2026', url: 'https://www.latimes.com/business/story/2026-01-26/nvidia-invests-additional-2-billion-in-coreweave' },
      { name: 'NVIDIA Investor Relations', description: 'NVIDIA and Nebius partner to scale full-stack AI cloud', date: 'Mar 2026', url: 'https://investor.nvidia.com/news/press-release-details/2026/NVIDIA-and-Nebius-Partner-to-Scale-Full-Stack-AI-Cloud/' },
      { name: 'Saturn Cloud', description: 'GPU cloud comparison report', date: null, url: 'https://saturncloud.io/reports/gpu-cloud-comparison-report/' },
      { name: 'Siebert Financial', description: "NVIDIA's $57 billion flex and the death of the AI bubble call", date: null, url: 'https://blog.siebert.com/nvidias-57-billion-flex-and-the-death-of-the-ai-bubble-call' },
      { name: 'Oracle Newsroom', description: 'Oracle and AMD expand partnership', date: 'Oct 2025', url: 'https://www.oracle.com/news/announcement/ai-world-oracle-and-amd-expand-partnership-to-help-customers-achieve-next-generation-ai-scale-2025-10-14/' },
      { name: 'AMD Investor Relations', description: 'AMD unveils vision for an open AI ecosystem', date: '2025', url: 'https://ir.amd.com/news-events/press-releases/detail/1255/amd-unveils-vision-for-an-open-ai-ecosystem-detailing-new-silicon-software-and-systems-at-advancing-ai-2025' },
      { name: 'Silicon Republic', description: 'Anthropic, Google, Broadcom announce 3.5 GW TPU deal', date: null, url: 'https://www.siliconrepublic.com/machines/anthropic-google-broadcom-announce-3-5gw-tpu-deal' },
      { name: 'Jon Peddie Research', description: "Broadcom's $100B custom silicon bet", date: null, url: 'https://www.jonpeddie.com/news/broadcoms-100b-custom-silicon-bet/' },
      { name: 'Futurum Group', description: "Anthropic's gigawatt-scale TPU deal with Broadcom creates a structural advantage", date: null, url: 'https://futurumgroup.com/insights/anthropics-gigawatt-scale-tpu-deal-with-broadcom-creates-a-structural-advantage/' },
      { name: 'The Next Web', description: 'CoreWeave agrees multi-year GPU cloud deal with Anthropic', date: null, url: 'https://thenextweb.com/news/coreweave-has-agreed-a-multi-year-gpu-cloud-deal-with-anthropic-to-power-claude-at-production-scale-its-second-major-ai-infrastructure-announcement-in-48-hours' },
    ],
  },
  {
    id: 'sec-filings',
    label: 'SEC Filings & Investor Relations',
    sources: [
      { name: 'NVIDIA Investor Relations', description: 'SEC filings — data center revenue, supply agreements, related-party transactions', date: null, url: 'https://investor.nvidia.com/financial-info/sec-filings' },
      { name: 'AMD Investor Relations', description: 'SEC filings — data center segment, customer concentration, ASIC arrangements', date: null, url: 'https://ir.amd.com/sec-filings' },
      { name: 'Broadcom Investor Relations', description: 'SEC filings — custom ASIC revenue, hyperscaler customer disclosures', date: null, url: 'https://investors.broadcom.com/sec-filings' },
      { name: 'Marvell Investor Relations', description: 'SEC filings — AI ASIC program disclosures, data center revenue', date: null, url: 'https://investor.marvell.com/sec-filings' },
      { name: 'Intel Investor Relations', description: 'SEC filings — foundry revenue, Gaudi accelerator program', date: null, url: 'https://www.intc.com/filings-reports/sec-filings' },
      { name: 'TSMC Investor Relations', description: 'Annual reports and investor presentations — advanced packaging, CoWoS capacity, customer mix', date: null, url: 'https://investor.tsmc.com/english/annual-reports' },
      { name: 'SEC EDGAR', description: 'CoreWeave S-1 and post-IPO filings — GPU fleet, customer contracts, NVIDIA relationship', date: null, url: 'https://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&company=coreweave&CIK=&type=&dateb=&owner=include&count=40&search_text=&action=getcompany' },
      { name: 'Oracle Investor Relations', description: 'SEC filings — Stargate commitment, cloud infrastructure capex', date: null, url: 'https://investor.oracle.com/sec-filings/default.aspx' },
      { name: 'Microsoft Investor Relations', description: 'SEC filings — Azure AI infrastructure, OpenAI partnership, capex', date: null, url: 'https://www.microsoft.com/en-us/investor/sec-filings.aspx' },
      { name: 'Alphabet Investor Relations', description: 'SEC filings — TPU program, GCP infrastructure, Broadcom/Marvell ASIC contracts', date: null, url: 'https://abc.xyz/investor/' },
      { name: 'Amazon Investor Relations', description: 'SEC filings — AWS Trainium/Inferentia programs, capex guidance', date: null, url: 'https://ir.aboutamazon.com/sec-filings/default.aspx' },
      { name: 'Meta Investor Relations', description: 'SEC filings — MTIA program, data center capex, GPU procurement', date: null, url: 'https://investor.fb.com/sec-filings/default.aspx' },
    ],
  },
  {
    id: 'epoch-ai',
    label: 'Epoch AI Datasets',
    sources: [
      { name: 'Epoch AI', description: 'AI chip sales data explorer — quarterly accelerator shipments and revenue by manufacturer (CC-BY)', date: null, url: 'https://epoch.ai/data/ai-chip-sales' },
      { name: 'Epoch AI', description: 'AI chip sales documentation — full methodology and per-manufacturer estimation approach', date: null, url: 'https://epoch.ai/data/ai-chip-sales-documentation' },
      { name: 'Epoch AI', description: 'AI chip owners — distribution of AI chips across hyperscalers, labs, and neoclouds', date: 'Apr 2026', url: 'https://epoch.ai/data/ai-chip-owners' },
      { name: 'Epoch AI', description: 'Frontier data centers — open database of large AI campuses via satellite and permit data', date: 'Apr 2026', url: 'https://epoch.ai/data/frontier-data-centers' },
      { name: 'Epoch AI', description: 'GPU clusters database — 500+ training and inference facilities', date: 'Apr 2026', url: 'https://epoch.ai/data/gpu-clusters' },
      { name: 'Epoch AI', description: 'ML hardware database — key specs on 170+ AI accelerators', date: 'Dec 2025', url: 'https://epoch.ai/data/machine-learning-hardware' },
      { name: 'Epoch AI', description: 'AI companies — revenue, funding, staff, and compute for major AI firms', date: 'Apr 2026', url: 'https://epoch.ai/data/ai-companies' },
      { name: 'Epoch AI', description: 'Supply chain constraints — CoWoS packaging, HBM, and advanced logic capacity in 2025', date: '2025', url: 'https://epoch.ai/data-insights/ai-chip-supply-chain-constraints' },
      { name: 'Epoch AI', description: 'Global AI compute growth — capacity doubling every ~7 months', date: null, url: 'https://epoch.ai/data-insights/ai-chip-production' },
    ],
  },
  {
    id: 'industry-research',
    label: 'Industry Research & Market Data',
    sources: [
      { name: 'SIA', description: 'Monthly semiconductor sales, policy briefs, and trade statistics', date: null, url: 'https://www.semiconductors.org/resources/' },
      { name: 'SEMI', description: 'Fab equipment spending, silicon shipment data, and quarterly industry reports', date: null, url: 'https://www.semi.org/en/resources/market-data' },
      { name: 'WSTS', description: 'Official global semiconductor revenue and forecast data', date: null, url: 'https://www.wsts.org/' },
      { name: 'TrendForce', description: 'Quarterly DRAM, NAND, and foundry reports plus AI ASIC shipment forecasts', date: null, url: 'https://www.trendforce.com/' },
      { name: 'Omdia', description: 'GPU market share and AI chip customer allocation estimates', date: null, url: 'https://omdia.tech.informa.com/' },
      { name: 'IDC', description: 'Quarterly semiconductor, server, and data-center market trackers', date: null, url: 'https://www.idc.com/' },
      { name: 'Gartner', description: 'AI infrastructure forecasts and semiconductor market analysis', date: null, url: 'https://www.gartner.com/en/industries/high-tech' },
      { name: 'TechInsights', description: 'Die-level analysis, wafer fab capacity, and process node data', date: null, url: 'https://www.techinsights.com/' },
      { name: "Dell'Oro Group", description: 'Quarterly data-center capex, networking, and cloud infrastructure trackers', date: null, url: 'https://www.delloro.com/' },
      { name: 'Yole Group', description: 'Advanced packaging, 3D IC, and chiplet market reports', date: null, url: 'https://www.yolegroup.com/' },
      { name: 'VLSI Research', description: 'Chip equipment market share and fabrication economics', date: null, url: 'https://vlsiresearch.com/' },
      { name: 'SemiAnalysis', description: 'Dylan Patel — GPU supply chains, custom ASIC economics, CoWoS capacity, HBM supply/demand', date: null, url: 'https://www.semianalysis.com/' },
      { name: 'Fabricated Knowledge', description: 'Semiconductor investment-focused newsletter', date: null, url: 'https://www.fabricatedknowledge.com/' },
    ],
  },
  {
    id: 'earnings',
    label: 'Earnings Calls & Investor Presentations',
    sources: [
      { name: 'NVIDIA Investor Relations', description: 'GTC keynotes and earnings transcripts — GPU demand, hyperscaler disclosures, supply chain outlook', date: null, url: 'https://investor.nvidia.com/events-and-presentations/events-and-presentations' },
      { name: 'Broadcom Investor Relations', description: 'Earnings call transcripts — custom ASIC revenue guidance, hyperscaler XPU disclosures, TAM estimates', date: null, url: null },
      { name: 'AMD Investor Relations', description: '"Advancing AI" event transcripts — MI300X/MI350 customer adoption, Instinct GPU roadmap', date: null, url: 'https://ir.amd.com/news-events/events-presentations' },
      { name: 'TSMC Investor Relations', description: 'Quarterly earnings calls — CoWoS capacity, customer demand, leading-edge node economics', date: null, url: 'https://investor.tsmc.com/english/quarterly-results' },
      { name: 'Marvell Investor Relations', description: 'Earnings and investor day — AI ASIC program progress, hyperscaler TAM projections, 2026-2028 roadmap', date: null, url: 'https://investor.marvell.com/events-and-presentations' },
    ],
  },
  {
    id: 'government',
    label: 'Government & Trade Data',
    sources: [
      { name: 'U.S. Bureau of Industry and Security', description: 'Export control rules — Entity List, Advanced Computing Rule, chip export restrictions', date: null, url: 'https://www.bis.gov/' },
      { name: 'SEC EDGAR', description: 'Full-text search — deal terms, supply agreements, related-party transactions across public filings', date: null, url: 'https://efts.sec.gov/LATEST/search-index?q=' },
      { name: 'USITC DataWeb', description: 'Monthly semiconductor import/export data by HTS code', date: null, url: 'https://dataweb.usitc.gov/' },
    ],
  },
  {
    id: 'research-policy',
    label: 'Research & Policy Organizations',
    sources: [
      { name: 'Stanford HAI', description: 'AI Index report — annual compute trends, AI investment, policy developments', date: null, url: 'https://aiindex.stanford.edu/' },
      { name: 'Georgetown CSET', description: 'Semiconductor supply chain and AI policy research', date: null, url: 'https://cset.georgetown.edu/' },
      { name: 'RAND Corporation', description: 'Semiconductor and AI security analysis', date: null, url: 'https://www.rand.org/topics/semiconductors.html' },
    ],
  },
  {
    id: 'company-descriptions',
    label: 'Company Descriptions',
    sources: [
      { name: 'Nanalyze', description: 'NVIDIA — GPU history and investment context', date: null, url: 'https://www.nanalyze.com/2017/05/investing-gpus-ai-amd-vs-nvidia' },
      { name: 'InsiderTrades', description: 'AMD — corporate overview', date: null, url: 'https://www.insidertrades.info/company/AMD-Advanced_Micro_Devices' },
      { name: 'FirmsWorld', description: 'Broadcom — deep-dive company profile', date: '2025', url: 'https://firmsworld.com/broadcom-inc' },
      { name: 'CompWorth', description: 'Marvell — strategic position and company metrics', date: null, url: 'https://compworth.com/company/marvell-semiconductor' },
      { name: 'Scribd', description: 'Intel — organizational overview', date: null, url: 'https://www.scribd.com/doc/204585248/Study-of-Intel-Corporation' },
      { name: 'Kavout', description: 'Groq — LPU benchmarks vs NVIDIA, AMD, Intel', date: null, url: 'https://www.kavout.com/blog/groq-lpu-chip-a-game-changer-in-the-high-performance-ai-chip-market-challenging-nvda-amd-intel/' },
      { name: 'Samsung Semiconductor', description: 'Samsung Foundry — business area overview', date: null, url: 'https://semiconductor.samsung.com/about-us/business-area/foundry' },
      { name: 'CanvasBusinessModel', description: 'TSMC — how it works (2026 profile)', date: '2026', url: 'https://canvasbusinessmodel.com/blogs/how-it-works/taiwan-semiconductor-manufacturing-company-how-it-works' },
      { name: 'Benzinga', description: 'Coherent — silicon photonics partnership with Tower', date: 'Mar 2026', url: 'https://www.benzinga.com/trading-ideas/movers/26/03/51413577/tower-semiconductor-stock-surges-after-coherent-silicon-photonics-breakthrough' },
      { name: 'GlobalData', description: 'Lumentum — company profile and product portfolio', date: null, url: 'https://www.globaldata.com/company-profile/lumentum-holdings-inc' },
      { name: 'Bullfincher', description: 'Qualcomm — segments and product overview', date: null, url: 'http://bullfincher.io/companies/qualcomm-incorporated/overview' },
      { name: 'Bluebird Electric', description: 'Arm Holdings — semiconductor and software design company history', date: null, url: 'http://www.bluebird-electric.net/artificial_intelligence_autonomous_robotics/microprocessors/ARM_Holdings_PLC_Public_Limited_Company_Cambridge_UK.htm' },
      { name: 'Synopsys Careers', description: 'Synopsys — EDA company role overview', date: null, url: 'https://careers.synopsys.com/job/bengaluru/sr-software-development-engineer-eda/44408/91539646592' },
      { name: 'Morningstar', description: 'Cadence — EDA industry leader report', date: null, url: 'https://www.morningstar.com/company-reports/1305214-cadence-design-systems-is-a-leader-in-the-critical-eda-space' },
      { name: 'EveryDev.ai', description: 'SambaNova — RDU and dataflow AI infrastructure', date: null, url: 'https://everydev.ai/developers/sambanova-systems' },
      { name: 'VentureBeat', description: 'Lightmatter — photonic AI accelerator chip details', date: null, url: 'https://venturebeat.com/ai/photonics-startup-lightmatter-details-p1-its-ai-optical-accelerator-chip' },
      { name: 'Inside HPC', description: 'Celestial AI — Photonic Fabric $175M Series C', date: 'Mar 2024', url: 'https://insidehpc.com/2024/03/photonic-fabric-company-celestial-ai-closes-175m-series-c' },
      { name: 'Ainvest', description: 'd-Matrix — AI inference chip, Microsoft-backed', date: 'Nov 2024', url: 'https://www.ainvest.com/news/ai-chip-revolution-d-matrix-challenges-nvidia-with-innovative-inference-technology-24111010b04da69df9687d1e' },
      { name: 'Ayar Labs', description: 'Ayar Labs — GUC partnership for co-packaged optics', date: 'Nov 2025', url: 'http://ayarlabs.com/news/guc-and-ayar-labs-partner-to-advance-co-packaged-optics-for-hyperscalers' },
      { name: 'Definable AI', description: 'Rivos — Meta acquires RISC-V AI chip startup', date: null, url: 'https://www.linkedin.com/posts/definable-ai_meta-platforms-has-acquired-rivos-a-silicon-activity-7379090307025440768-SHVw' },
      { name: 'Transparity', description: 'Microsoft — Azure cloud infrastructure for AI', date: null, url: 'https://www.transparity.com/azure/microsoft-azure-cloud-infrastructure-for-ai' },
      { name: 'Parameter', description: 'Google/Alphabet — TPU and AI capex strategy', date: null, url: 'https://parameter.io/alphabet-googl-stock-google-tpu-chips-gain-ground-against-nvidia-in-ai-market' },
      { name: 'LinkedIn', description: 'AWS — Inferentia and Trainium chip overview', date: null, url: 'https://www.linkedin.com/pulse/aws-inferentia-trainium-nadir-riyani-0imtf' },
      { name: 'The Next Platform', description: 'Meta — Llama API service launch at LlamaCon 2025', date: 'Apr 2025', url: 'https://www.nextplatform.com/ai/2025/04/30/with-its-llama-api-service-meta-platforms-finally-becomes-a-cloud/1639833' },
      { name: 'TechTarget', description: 'Oracle — OCI positioning and Stargate deals', date: null, url: 'https://www.techtarget.com/searchCloudComputing/news/366631471/Beyond-Stargate-Oracle-OCI-ups-cloud-infrastructure-appeal' },
      { name: 'Trusted Reviews', description: 'Apple — Private Cloud Compute explainer', date: null, url: 'https://www.trustedreviews.com/explainer/what-is-private-cloud-compute-4557382' },
      { name: 'IoT World Today', description: 'Tesla — Dojo program wind-down', date: null, url: 'https://www.iotworldtoday.com/transportation-logistics/tesla-drops-dojo-ai-training-supercomputer' },
      { name: 'SoftBank Group', description: 'SoftBank — Stargate expansion press release', date: 'Sep 2025', url: 'https://group.softbank/en/news/press/20250924' },
      { name: 'BlackRock', description: 'BlackRock — AI Infrastructure Partnership announcement', date: 'Mar 2025', url: 'https://www.blackrock.com/corporate/newsroom/press-releases/article/corporate-one/press-releases/ai-infrastructure-partnership' },
      { name: 'Prezi', description: 'CoreWeave — GPU cloud infrastructure analysis', date: null, url: 'https://prezi.com/p/51ozxjflbssr/coreweave-analyzing-the-future-of-gpu-cloud-infrastructure' },
      { name: 'The Outpost', description: 'Nebius — capex surge on GPU and data centers', date: null, url: 'https://theoutpost.ai/news-story/nebius-group-capex-jumps-to-2-1-billion-as-ai-cloud-firm-expands-gpu-and-data-center-footprint-23757' },
      { name: 'IT Research Online', description: 'Lambda — $320M Series C funding', date: null, url: 'https://www.itresearchonline.com/lambda-raises-320-million-for-gpu-cloud-focused-on-ai' },
      { name: 'Electronic Specifier', description: 'Cerebras — SEMI award for AI accelerator technology', date: null, url: 'https://www.electronicspecifier.com/news/awards/cerebras-systems-wins-semi-award-for-ai-accelerator-technology/' },
      { name: 'ENGtechnica', description: 'Nscale — UK AI infrastructure, Stargate partnership', date: 'Sep 2025', url: 'https://engtechnica.com/nscale-expands-uk-ai-infrastructure-with-stargate-platform' },
      { name: 'Data Center Map', description: 'Crusoe — Stargate Abilene campus overview', date: null, url: 'https://www.datacentermap.com/usa/texas/abilene/abilene-clean-campus' },
      { name: 'TS2', description: 'IREN/Iris Energy — $9.7B Microsoft deal', date: 'Nov 2025', url: 'https://ts2.tech/en/from-bitcoin-miner-to-ai-cloud-powerhouse-iris-energys-meteoric-rise-iren-stock-soars-on-9-7b-microsoft-deal' },
      { name: 'AllGPTs', description: 'OpenAI — GPT Store and GPT-4 customization overview', date: null, url: 'https://allgpts.co/blog/customizing-chatgpt-with-openai-gpt-com' },
      { name: 'DevOpsSchool', description: 'Anthropic — Claude 3.5 Sonnet profile', date: null, url: 'https://www.devopsschool.com/blog/anthropic-claude-3-5-sonnet-large-language-model-llm' },
      { name: 'Grok Musk World', description: 'xAI — Colossus supercomputer specs', date: 'Feb 2026', url: 'https://grokmuskworld.com/xai-colossus-supercomputer-2026-grok-5-training' },
      { name: 'BGR', description: 'io Products — OpenAI closes $6.5B Jony Ive deal', date: 'Jul 2025', url: 'https://www.bgr.com/business/chatgpt-hardware-confirmed-as-openai-closes-6-5b-deal-for-jony-ive-startup' },
      { name: 'Aligned Data Centers', description: 'Aligned Data Centers — Northern Virginia hyperscale campus', date: 'Jul 2022', url: 'https://aligneddc.com/blog/aligned-data-centers-expands-presence-in-northern-virginia-with-new-sterling-hyperscale-campus' },
      { name: 'Applied Digital Investor Relations', description: 'Applied Digital — Ellendale ND HPC data-center milestone', date: 'Dec 2024', url: 'https://ir.applieddigital.com/news-events/press-releases/detail/114/applied-digital-announces-ellendale-hpc-data-center' },
      { name: 'Data Center Dynamics', description: 'Core Scientific — rejects CoreWeave acquisition offer', date: null, url: 'https://www.datacenterdynamics.com/en/news/core-scientific-rejects-coreweave-acquisition-offer' },
      { name: 'Data Center Dynamics', description: 'Galaxy Digital — $1.4B Helios campus financing', date: null, url: 'https://www.datacenterdynamics.com/en/news/galaxy-digital-closes-14bn-debt-facility-for-helios-data-center-campus-in-texas' },
      { name: 'TweakTown', description: 'SK Hynix — HBM4 hiring and foundry outsourcing plans', date: null, url: 'https://www.tweaktown.com/news/99240/sk-hynix-looking-for-semiconductor-engineers-48-positions-in-hbm-finfet-transistor-experts/index.html' },
      { name: 'All About Circuits', description: 'Micron — HBM3E DRAM leadership alongside Samsung and SK Hynix', date: null, url: 'https://www.allaboutcircuits.com/news/samsung-micron-sk-hynix-lead-charge-hbm3e-dram' },
      { name: 'Samsung Semiconductor', description: 'Samsung Memory — HBM product page', date: null, url: 'https://semiconductor.samsung.com/dram/hbm' },
      { name: 'Yahoo Finance', description: 'ASML — EUV monopoly and advanced-packaging plans', date: null, url: 'https://finance.yahoo.com/news/asml-holding-asml-plans-expand-134738321.html' },
      { name: 'Granite Firm', description: 'Applied Materials — equipment product line and revenue mix', date: 'Apr 2024', url: 'https://www.granitefirm.com/blog/us/2024/04/18/applied-materials' },
      { name: 'Abachy', description: 'Lam Research — semiconductor processing equipment portfolio', date: null, url: 'https://abachy.com/catalog/semiconductor-equipment/lam-research' },
      { name: 'Tokio Express', description: 'Tokyo Electron — coater/developer market share, ASML partnership', date: null, url: 'http://tokiox.com/wp/tokyo-electron-provided-to-asml-next-generation-coater-developer?lang=en' },
      { name: 'Monexa', description: 'KLA — process control growth and product portfolio', date: 'Feb 2025', url: 'https://www.monexa.ai/blog/kla-corporation-navigating-semiconductor-process-c-KLAC-2025-02-19' },
      { name: 'SemiMedia', description: 'Shin-Etsu Chemical — wafer and photoresist investments', date: null, url: 'https://www.semimedia.cc/tag/shin-etsu-chemical' },
      { name: 'UniversityWafer', description: 'SUMCO — silicon wafer product overview', date: null, url: 'https://www.universitywafer.com/sumco-wafers.html' },
      { name: 'Onto Innovation', description: 'Onto Innovation — AI and ML in semiconductor metrology', date: null, url: 'https://ontoinnovation.com/resources/ai-and-ml-in-semi-manufacturing-inspection-and-metrology' },
      { name: 'Entegris', description: 'Entegris — Digital Specialty Chemicals brand page', date: null, url: 'https://www.entegris.com/en/home/brands/digital-specialty-chemicals.html' },
      { name: 'TickerTable', description: 'Arista Networks — company overview and products', date: null, url: 'https://tickertable.com/arista-networks' },
      { name: 'Astera Labs', description: 'Astera Labs — CXL and PCIe technology leadership', date: null, url: 'https://www.asteralabs.com/news/astera-labs-advances-cxl-and-pcie-technology-leadership-at-fms-2024' },
      { name: 'CCB Journal', description: 'Mellanox — NVIDIA acquisition advisory', date: null, url: 'https://ccbjournal.com/news/jones-day-advises-nvidia-in-acquisition-of-mellanox-technologies-ltd' },
      { name: 'Vella Times', description: 'Cisco — Silicon One G300 AI networking chip', date: null, url: 'https://vellatimes.com/cisco-silicon-one-g300-ai-networking-chip-revealed-for-ai' },
      { name: 'Credo Semi', description: 'Credo — HiWire Active Electrical Cables production announcement', date: 'Sep 2019', url: 'https://credosemi.com/news/credo-announces-production-availability-of-hiwire-active-electrical-cables/' },
      { name: 'Sahm Capital', description: 'Amkor — advanced packaging investor presentation', date: 'Feb 2026', url: 'https://www.sahmcapital.com/news/content/amkor-technology-publishes-investor-presentation-on-advanced-packaging-global-osat-footprint-and-growth-strategy-2026-02-24' },
      { name: 'Seeking Alpha', description: 'ASE Technology — largest global OSAT profile', date: null, url: 'https://seekingalpha.com/article/4746451-ase-technology-holding-the-undervalued-largest-osat-in-the-world' },
      { name: 'Data Center Dynamics', description: 'Constellation — Meta 20-year PPA for Clinton nuclear plant', date: null, url: 'https://www.datacenterdynamics.com/en/news/meta-signs-20-year-ppa-with-constellation-for-entire-output-of-illinois-nuclear-power-plant' },
      { name: 'Nasdaq', description: 'Talen Energy — Amazon nuclear partnership expansion', date: null, url: 'https://www.nasdaq.com/articles/talen-energy-expands-nuclear-partnership-amazon-supply-carbon-free-energy-aws-data-centers' },
      { name: 'Industrial Info', description: 'Kairos Power — Google and TVA SMR partnership', date: null, url: 'https://www.industrialinfo.com/news/article/google-to-partner-with-tva-kairos-power-for-smr-in-oak-ridge-tn--345223' },
      { name: 'Power Texas Forward', description: 'Vistra — Comanche Peak nuclear power plant fact sheet', date: null, url: 'https://powertexasforward.com/comanche-peak' },
      { name: 'Utility Dive', description: 'X-energy — Amazon SMR partnership announcement', date: null, url: 'https://www.utilitydive.com/news/amazon-small-modular-reactor-deals-nuclear-dominion-x-energy-energy-northwest/730022' },
      { name: 'Brookfield Renewable', description: 'Brookfield Renewable — Google hydro framework agreement', date: 'Jul 2025', url: 'https://bep.brookfield.com/press-releases/bepc/brookfield-and-google-sign-hydro-framework-agreement-deliver-3000-mw-homegrown' },
      { name: 'BusinessWire', description: 'Sage Geosystems — Meta geothermal partnership', date: 'Aug 2024', url: 'https://www.businesswire.com/news/home/20240826755596/en/Sage-Geosystems-and-Meta-Announce-Agreement-for-Next-Generation-Geothermal-Power-Generation' },
      { name: 'Construction Review Online', description: 'Entergy — Meta Louisiana energy infrastructure deal', date: null, url: 'https://constructionreviewonline.com/meta-entergy-to-fund-energy-infrastructure-for-louisiana-data-center-in-landmark-utility-deal' },
      { name: 'SiliconANGLE', description: 'Dell — $5B+ AI server deal with xAI', date: 'Feb 2025', url: 'https://siliconangle.com/2025/02/14/report-dell-close-inking-5b-ai-server-deal-xai/' },
      { name: 'Monexa', description: 'HPE — Juniper acquisition and AI-native networking', date: 'Jul 2025', url: 'https://www.monexa.ai/blog/hewlett-packard-enterprise-hpe-juniper-acquisition-HPE-2025-07-29' },
      { name: 'TweakTown', description: "Foxconn — Taiwan's fastest supercomputer with NVIDIA Blackwell", date: null, url: 'https://www.tweaktown.com/news/100969/nvidia-foxconn-to-build-taiwans-fastest-supercomputer-with-blackwell-gb200-nvl72-ai-servers/index.html' },
      { name: 'Forbes', description: 'ZT Systems — AMD acquisition for GPU rack design', date: 'Aug 2024', url: 'https://www.forbes.com/sites/patrickmoorhead/2024/08/19/amd-boosts-gpu-server-design-capabilities-with-zt-systems-acquisition' },
      { name: 'Financial Content', description: 'Super Micro — liquid-cooled AI server deep dive', date: 'Jan 2026', url: 'https://markets.financialcontent.com/stocks/article/finterra-2026-1-22-the-liquid-cooled-titan-a-deep-dive-into-super-micro-computer-smci' },
      { name: 'UAE Preferred', description: 'GlobalFoundries — $16B US semiconductor investment', date: null, url: 'https://www.uaepreferred.com/perspectives/uae-backed-globalfoundries-plans-16bn-us-semiconductor-investment' },
      { name: 'DCF Modeling', description: 'UMC — history, mission, and mature-node focus', date: null, url: 'https://www.dcfmodeling.com/blogs/history/umc-history-mission-ownership' },
      { name: 'WccfTech', description: 'SMIC — 7 nm N+1 node production announcement', date: null, url: 'https://wccftech.com/chinese-semiconductor-manufacturer-smic-to-introduce-7nm-node' },
      { name: 'Semiconductor Today', description: 'Tower Semiconductor — Intel acquisition attempt', date: 'Feb 2022', url: 'https://www.semiconductor-today.com/news_items/2022/feb/intel-tower-160222.shtml' },
    ],
  },
  {
    id: 'news-analysis',
    label: 'News & Analysis',
    sources: [
      { name: 'Reuters Technology', description: 'Ongoing coverage of AI infrastructure deals, hyperscaler capex, chip supply chains', date: null, url: 'https://www.reuters.com/technology/' },
      { name: 'Bloomberg Terminal', description: 'Semiconductor supply chain data, capex trackers, earnings estimates (paid subscription)', date: null, url: 'https://www.bloomberg.com/professional/' },
      { name: 'The Information', description: 'Exclusive AI and tech deal reporting, hyperscaler strategy coverage (paid subscription)', date: null, url: 'https://www.theinformation.com/' },
      { name: 'Data Center Dynamics', description: 'AI data-center capex analysis and hyperscaler power and build programs', date: null, url: 'https://www.datacenterdynamics.com/' },
      { name: 'Deloitte', description: '2026 global semiconductor industry outlook', date: '2026', url: 'https://www.deloitte.com/us/en/insights/industry/technology/technology-media-telecom-outlooks/semiconductor-industry-outlook.html' },
      { name: 'J.P. Morgan', description: 'Eye on the Market — AI capex cycle analysis (Cembalest)', date: null, url: null },
    ],
  },
]
